# Generated by Django 4.1.1 on 2022-10-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userId", models.EmailField(max_length=20)),
            ],
        ),
    ]
