# Generated by Django 4.1.1 on 2022-10-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitter", "0002_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="fileSize",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
