# Generated by Django 4.1.1 on 2022-11-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitter", "0004_location_lat_location_long"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="thumnail",
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
