# Generated by Django 4.1.1 on 2022-11-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petsitter", "0007_alter_document_thumnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document", name="thumnail", field=models.TextField(),
        ),
    ]
