# Generated by Django 4.1.3 on 2022-12-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitter', '0010_alter_document_thumnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadedImg', models.ImageField(upload_to='Pet Images/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
